#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend smithi.tech
    timeout client  30000
    bind 0:80
    default_backend smithi.tech_backend

backend smithi.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 228560-web-01 18.214.87.88:80 check
    server 228560-web-02 54.237.104.218:80 check
EOT

sudo service haproxy restart
